### ISSUE TITLE
New Ruleset

### ISSUE THREAD

**Issue by nataliesiejczuk** [Connexions/baked-pdf#4]
**Description**
As an OpenStax developer, I want to prototype a ruleset to replace DocBook, so that I can create elements of a book in a more efficient manner.

**Technical Notes**
Create a ruleset to create elements of a book that would typically be created by DocBook.
The following are specific elements to reproduce:
TOC
units (optional)
chapters
Pages in chapters
Page number
Page numbering
Appendices (if any exist)
Glossary
Compile are terms to the EOB
Index
Pulls location of terms in content
Allow marking items as indexable so concepts can be added to the index; and document
Attribution pages
This is removed before books are printed, so maybe this does not need to be recreated.
Footnote processing
Webview is handling footnotes correctly, so there may be no work to do.

**Acceptance Criteria**

**Link to Story in Epic Document**
https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.dlocn4fdnf72

**Comment by openstaxalina** [comment]
This is complete - closing.
